import numpy


def around_black(color_1: tuple[int, int, int]) -> bool: ...

def around_white(color_1: tuple[int, int, int]) -> bool: ...

def eq_color(color_1: tuple[int, int, int], color_2: tuple[int, int, int])->bool:...

def minus_color(color_1: tuple[int, int, int], color_2: tuple[int, int, int]) -> tuple[int, int, int]: ...

def abs_minus_color(color_1: tuple[int, int, int], color_2: tuple[int, int, int]) -> tuple[int, int, int]: ...


def split_captcha(image: numpy.ndarray[numpy.ndarray[tuple[int, int, int]]]) -> tuple[int, int]: ...


def get_all_icons(image: numpy.ndarray[numpy.ndarray[tuple[int, int, int]]],row:int=None,column:int=None) ->\
        numpy.ndarray[numpy.ndarray[tuple[int, int, int]]]: ...

def split_icons(image: numpy.ndarray[numpy.ndarray[tuple[int, int, int]]], max_icon_width:int=21) -> \
        list[list[int]]: ...

def create_icons( image:numpy.ndarray[numpy.ndarray[tuple[int, int, int]]],icons:list[list[int]],
                  max_icon_width:int=21) ->numpy.ndarray[numpy.ndarray[numpy.ndarray[tuple[int, int, int]]]]: ...
